# Generated by Django 4.1.3 on 2022-11-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('prenom', models.CharField(max_length=128)),
                ('telephone', models.CharField(max_length=128)),
            ],
        ),
    ]
