# Generated by Django 4.1.3 on 2022-11-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='nom',
            field=models.CharField(max_length=256),
        ),
    ]
