# Generated by Django 4.1.3 on 2022-11-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0002_alter_contacts_nom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
