# Generated by Django 4.1.3 on 2022-11-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0003_rename_contacts_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='entreprise',
            field=models.BigIntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='prenom',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
