# Generated by Django 4.1.3 on 2022-11-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0004_contact_entreprise_alter_contact_prenom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='entreprise',
            field=models.BigIntegerField(default=True),
        ),
    ]
