# Generated by Django 4.1.3 on 2022-11-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0005_alter_contact_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='entreprise',
            field=models.BigIntegerField(default=False),
        ),
    ]
